source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘10.0’
use_frameworks!

target 'Example' do
    #pod 'CZKit/Date'
    

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Example'
            target.build_configurations.each do |config|                            
                config.build_settings['SWIFT_VERSION'] = '5'
            end
        end
    end
end
